### ISSUE TITLE
Instructions and is this complete to play? 

### ISSUE THREAD

**Issue by coreybruce** [kaspermeerts/supermarioland#1]
Hi just wondering you can give proper instruction on how to compile this also is this completed and playable?

**Comment by kaspermeerts** [comment]
To assemble the project, you need a copy of the original ROM as described in the [README](https://github.com/kaspermeerts/supermarioland/blob/master/README.md). My disassembly is incomplete, and the holes need to be filled in with the original data. For copyright reasons I cannot include it in the repository.

Then you need to have [RGBDS](https://github.com/gbdev/rgbds) installed, navigate to the directory of the project, and run `make`. I have only tested it on Linux, I have no experience with either Windows or macOS. You will need some knowledge of the command line. The instructions found [here](https://github.com/pret/pokered/blob/master/INSTALL.md) for the Pokemon Red disassembly probably apply.

The project is, for now, very incomplete. Not only is not all of the code disassembled, what has been disassembled hasn't been properly documented yet. I will take it up again one day, but for now I have nothing planned.

**Comment by coreybruce** [comment]
Yeah don't worry I am on Manjaro Linux. so does this compile to a native binary or not yet?

**Comment by kaspermeerts** [comment]
Oh, that was never my intent. I simply want to recreate something akin to the original source code, with all variables and routines identified and documented. The architecture of the Game Boy is so different from modern PCs, that getting it to compile would be near impossible, and not worth the effort compared to just running it in an emulator. I'm sorry to disappoint.

**Comment by coreybruce** [comment]
Ahh ok I see, it wouldn't be impossible if you have the code but it would be super awesome if I could compile and  run it on my Raspberry pi 4 natively :D

This is still a very awesome project, keep up the good work!
